import { Metadata } from "next";
import { notFound } from "next/navigation";
import { AuditResults } from "@/components/audit/AuditResults";
import { getAuditByPublicId } from "@/lib/db/audits";
import { AuditResult } from "@/lib/audit/types";

export async function generateMetadata({
  params,
}: {
  params: Promise<{ publicId: string }>;
}): Promise<Metadata> {
  const { publicId } = await params;
  const audit = await getAuditByPublicId(publicId);

  if (!audit) {
    return {
      title: "Audit not found — StackSaver",
    };
  }

  const result = audit.result as AuditResult;

  return {
    title: `This AI stack could save $${result.totalAnnualSavings}/year`,
    description: `AI spend audit across ${result.input.tools.length} tools. Generated by StackSaver.`,
    openGraph: {
      title: `This AI stack could save $${result.totalAnnualSavings}/year`,
      description: `AI spend audit across ${result.input.tools.length} tools. Generated by StackSaver.`,
      type: "website",
    },
    twitter: {
      card: "summary_large_image",
      title: `This AI stack could save $${result.totalAnnualSavings}/year`,
      description: "Generated by StackSaver.",
    },
  };
}

export default async function PublicAuditPage({
  params,
}: {
  params: Promise<{ publicId: string }>;
}) {
  const { publicId } = await params;
  const audit = await getAuditByPublicId(publicId);

  if (!audit) {
    notFound();
  }

  const result = audit.result as AuditResult;

  return (
    <main className="mx-auto max-w-6xl px-4 py-10">
      <div className="mb-8 flex items-center justify-between">
        <a href="/" className="text-sm text-muted-foreground">
          ← StackSaver
        </a>

        <a href="/audit/new" className="text-sm font-medium">
          Run your own audit
        </a>
      </div>

      <AuditResults result={result} />
    </main>
  );
}